### ISSUE TITLE
curl: (7) Couldn't connect to server

### ISSUE THREAD

**Issue by lordraiden** [hotio/docker-cloudflare-ddns#1]
How can I trhoubleshoot this error?
curl: (7) Couldn't connect to server

> Executing usermod...
[cont-init.d] 00-start-container: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
**curl: (7) Couldn't connect to server**
2020-02-09 22:14:01 - [curl-wtfismyip.com] - [XXXXXXX.XXXXX.XX.XX] - [A] - Updating IP [XXXXXXXXXXXXXXXX] to [XXXXXXXXXXXX]: OK

**Comment by hotio** [comment]
Increase log level as a start

**Comment by hotio** [comment]
Found the issue, will be fixed shortly

**Comment by hotio** [comment]
do docker pull and re-create the container with the updated image, should be fixed now

**Comment by lordraiden** [comment]
That was quick, thanks a lot 👍 

Why if I use one of the dig... options I get this error?


Executing usermod...
[cont-init.d] 00-start-container: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
2020-02-10 19:46:54 - [dig-opendns.com] - [XXXXXXXXXXXX] - [A] - Returned IP by "dig-opendns.com" is not valid! Check your connection.

**Comment by hotio** [comment]
That means the ip fails the regex, you could try and do the command as found in the script manually inside the container....

**Comment by hotio** [comment]
`dig -4 A +short myip.opendns.com @resolver1.opendns.com` is the command, look at the output....
