### ISSUE TITLE
The requested URL returned error: 400

### ISSUE THREAD

**Issue by dazWiLLiE** [hotio/docker-cloudflare-ddns#2]
Installed the docker container today, created a token with:
```
Zone - Zone Settings - Read
Zone - Zone - Read
Zone - DNS - Edit

Zone resources:
Include - All zones
``` 

CF_ZONES: root site
CF_HOSTS: subdomains
CF_RECORDTYPES: A;A;A;A
CF_APITOKEN: the token

(not using the key, user or password variables)

From the log:

```
2020-03-01 13:36:44 - [dig-opendns.com] - [xxxx.xxxxxxxxx.xx] - [A] - Couldn't fetch DNS records from "Cloudflare"! Check your connection or configuration.
curl: (22) The requested URL returned error: 400
```

I turned off Argo thinking it was related, but still same error.
Ticked priviliged, restarted, no change.

Don't know where else to look? Cloudflare?

Edit: 
From a terminal inside the container:

```
curl -X GET "https://api.cloudflare.com/client/v4/user/tokens/verify" \
>      -H "Authorization: Bearer xxXxxxXxxxxXxxxXxxXxxxx" \
>      -H "Content-Type:application/json"
{"result":{"id":"xxxxxxxxxxxxxxxxxxxxxxxx","status":"active"},"success":true,"errors":[],"messages":[{"code":10000,"message":"This API Token is valid and active","type":null}]}
```

**Comment by hotio** [comment]
Seems like you misconfigured it if that's your config

**Comment by dazWiLLiE** [comment]
Where? Docker or Cloudflare?

**Comment by hotio** [comment]
Docket

**Comment by dazWiLLiE** [comment]
Oh, ok. I thought I followed your Readme correctly. I'll paste my config here then, let's see if I missed something:

```
Network type: Host
INTERVALL: 300
DETECTION_MODE: dig.opendns.com
LOG_LEVEL: 2
CF_USER:
CF_APIKEY:
CF_ZONES: xxxxxxx.xx
CF_HOSTS: x.x.xx;x.x.xx;x.x.xx;x.x.xx
CF_RECORDTYPES: A;A;A;A
INFLUXDB_ENABLED: False
CF_APITOKEN: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
PUID: xxxx
PGID: xxxx
UMASK: xxx
ARGS:
```
I have other containers running with no problem.

**Comment by dazWiLLiE** [comment]
My bad, the token was wrong. It's working now.

Last question: Will the ip for the rootdomain also get updated, or only the subdomains?

**Comment by hotio** [comment]
Your config is still wrong, give the readme another read...

**Comment by dazWiLLiE** [comment]
I need to set a zone for each host?

**Comment by hotio** [comment]
Yes

**Comment by dazWiLLiE** [comment]
Ok, thanks.
And finally...

Do I need to put the rootdomain in CF_HOSTS if I want to get it updated too?

**Comment by hotio** [comment]
Yes
