### ISSUE TITLE
Remember the TTL setting

### ISSUE THREAD

**Issue by walle89** [hotio/docker-cloudflare-ddns#3]
After each time the DNS record gets updated, it overrides the TTL setting to auto. Is it possible to either remember the setting value like it's done for the proxy setting, or maybe to have it as a configurable option?

Otherwise really great work you have done so far with this project.

**Comment by hotio** [comment]
should be fixed with https://github.com/hotio/docker-cloudflare-ddns/commit/139b0e10efcd3d0cbd97da4b00e32a88f966188a
