### ISSUE TITLE
Won't write new hosts

### ISSUE THREAD

**Issue by alexjustesen** [hotio/docker-cloudflare-ddns#4]
### Issue
While attempting to write a new host record on an existing zone, the script "Couldn't fetch DNS records from Cloudflare".

### Replicate steps
1. Remove zone from CF using the panel, or use new domain without zone records.
2. Restart container to trigger an update.

### Work Around
Set an initial zone value in CF and restart the container. The container will then successfully update the record.

**Comment by wouterstemgee** [comment]
Same issue here

**Comment by hotio** [comment]
Setting log level to 3 fixes it for the moment

**Comment by hotio** [comment]
Ps, creating records is not supported

**Comment by alexjustesen** [comment]
@hotio can I suggest an edit to the readme then to mention that unless I completely missed it? I switched from a different CF ddns container that did create them so I just assumed.

**Comment by hotio** [comment]
you didn't miss it, it's not mentioned. It's meant to update your dynamic ip....the value in the dns record is also used to verify wether we are actually updating an ipv4/6 record with an ipv4/6 adress and if the returned data by cloudflare is valid. so if the record isn't set or contains bogus info, it'll fail. I'll add a remark to the readme.
