### ISSUE TITLE
502 Error when implementing it in docker-compose.yaml

### ISSUE THREAD

**Issue by ALZERCODE** [hotio/docker-cloudflare-ddns#5]
Hey there,
I am new to docker and I tried to implement your service into my docker-compose.yaml file.
I am using:

1. wordpress
2. nginx
3. and an hypriot/rpi-mysql database

My docker-compose
[docker-compose.txt](https://github.com/hotio/docker-cloudflare-ddns/files/5045338/docker-compose.txt)
And my nginx.config file
[website_nginx_config.txt](https://github.com/hotio/docker-cloudflare-ddns/files/5045339/website_nginx_config.txt)

Without the dyndns-service my wordpress website runs perfecly. The dyndns service runs perfectly with and without the wordpress website. But as soon as I have both running I get an 502 Bad gateway error from cloudflare. If somebody has experienced the same or has an idea how I can get both running, I would be very happy to hear your solution. :)

Edit:
I also get this error from nginx
nginx        | 2020/08/08 13:17:26 [error] 19#19: *1 connect() failed (111: Connection refused) while connecting to upstream, client: *censored*, server: mydomainishere, request: "GET / HTTP/1.1", upstream: "http://*censored*/", host: "mydomainishere"
nginx        | 2020/08/08 13:17:26 [warn] 19#19: *1 upstream server temporarily disabled while connecting to upstream, client: *censored*, server: mydomainishere, request: "GET / HTTP/1.1", upstream: "http://*censored*/", host: "mydomainishere

I censored the upstream ips cause I am not quite sure what that is, but I guess its wordpress.

**Comment by hotio** [comment]
1) drop the quotes
2) where's the cloudflare-ddns log?
3) What does this have to do with nginx? my image just updates the ip on cloudlfare, that's it

**Comment by ALZERCODE** [comment]
Well I figured it out myself. I had to create an extra folder with an dockerfile and change the build location of the ddns service... So all services are fine, thanks for responding anyway.

**Comment by hotio** [comment]
I'm confused, but ok, happy to see it's resolved.
