### ISSUE TITLE
"An unexpected error ocurred" when reading zone list

### ISSUE THREAD

**Issue by cablespaghetti** [hotio/docker-cloudflare-ddns#6]
Hi. I've tried to deploy this and both with an api and my global key I get log output like this. Is there any way to get more detailed logs to find out what the problem is?

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-start-container: executing... 

----------------------------------------------------------------------
ENVIRONMENT
----------------------------------------------------------------------
PUID=1000
PGID=1000
UMASK=002
TZ=Etc/UTC
ARGS=
INTERVAL=300
DETECTION_MODE=dig-whoami.cloudflare
LOG_LEVEL=3
APPRISE=
CF_USER=<my-email>
CF_APIKEY=<my-global-key>
CF_APITOKEN=
CF_APITOKEN_ZONE=
CF_HOSTS=vpn.mydomain.com
CF_ZONES=mydomain.com
CF_RECORDTYPES=A
----------------------------------------------------------------------

Executing usermod...
usermod: no changes
Applying permissions to /config
Creating directory /config/app
[cont-init.d] 00-start-container: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
2020-08-14 09:56:22 -    INFO - IPv4 detected by [dig-whoami.cloudflare] is [my-ip-address].
2020-08-14 09:56:22 -    INFO - [1/1] [A] [mydomain.com] [vpn.mydomain.com] Reading zone list from Cloudflare.
2020-08-14 09:56:37 -   ERROR - [1/1] [A] [mydomain.com] [vpn.mydomain.com] An unexpected error occured!
2020-08-14 09:56:37 -    INFO - Going to sleep for [300] seconds...
```

**Comment by hotio** [comment]
https://github.com/hotio/docker-cloudflare-ddns#log-levels

**Comment by hotio** [comment]
`An unexpected error occured!``

This would however indicate that it's probably not a problem with Username/API keys, but somethin gmore serious

**Comment by cablespaghetti** [comment]
I'm already on log level 3 unfortunately. I wonder if it's something to do with running on Kubernetes. Yes if I exec in I can do all of that. I'll fork off and add lots of debug logs later on to see if I can figure it out.

**Comment by hotio** [comment]
normally it would return something like `{"success":false,"errors":[{"code":9106,"message":"Missing X-Auth-Email header"},{"code":9107,"message":"Missing X-Auth-Key header"}],"messages":[],"result":null}`

I check the success for false/true in 3 cases and else I give the error `An unexpected...`, so it not getting anything from cloudflare that looks like the above.

**Comment by cablespaghetti** [comment]
![image](https://user-images.githubusercontent.com/11150054/90281067-ded74580-de63-11ea-9a5d-69bc1101c862.png)

Thanks for your help. Something strange is going on in my K8S cluster with DNS search domains causing issues with this.
